### ISSUE TITLE
Update the site of the project

### ISSUE THREAD

**Issue by AlexWayfer** [shivanshs9/puppeteer-pdf#1]
Hello.

I see you've made nice fork, thank you.

But I see the original site in the description:

![image](https://user-images.githubusercontent.com/6510020/90250640-0bc83000-de45-11ea-96da-a0253080de0a.png)

I think, it'd be better to change it, for example, to https://www.npmjs.com/package/@shivanshs9/puppeteer-pdf

**Comment by shivanshs9** [comment]
Thank you for your suggestion! Have fixed it :)
